### ISSUE TITLE
web.log flooded with `ValueError: need more than 1 value to unpack`

### ISSUE THREAD

**Issue by debalance** [modusoft/lm-sensors#5]
With check-mk-raw-1.6.0p24 the following error messages flood my `web.log`:

```
2021-06-16 15:16:51,444 [40] [cmk.web 11724] /bvd_srv/check_mk/view.py?host=pve-1-bvd.bvd.indurad.x&site=bvd_srv&view_name=host Failed to parse perfdata 'k10temp-pci-00e3 Tctl=46.9;;0;;'
Traceback (most recent call last):
  File "/omd/sites/bvd_srv/lib/python/cmk/gui/plugins/metrics/utils.py", line 239, in parse_perf_data
    varname, value_text, value_parts = parse_perf_values(part)
  File "/omd/sites/bvd_srv/lib/python/cmk/gui/plugins/metrics/utils.py", line 180, in parse_perf_values
    varname, values = data_str.split("=", 1)
ValueError: need more than 1 value to unpack
```

I have tried to unterstand it and believe the problem to be that the perfdata string should not contain the checkname (`'k10temp-pci-00e3 `).
A lot of perfdata seems to be processed correctly though, I still get nicely rendered pnp4nagios graphs for these checks.

**Comment by cboseck** [comment]
This seams to be the same issue as #3.
Please try the latest code from the repository.

**Comment by debalance** [comment]
Thanks, problem solved, please make a new release for this.
